### PR TITLE
Rename bonus material notebooks

### PR DESCRIPTION
**Pull request by BHFock**
include word bonus in bonus material notebooks to help navigation of tutorial content

### CODE REVIEW

**Comment by pp-mo** [comment]
Hi @BHFock this looks sensible to me.

Did you want me to get involved here, e.g. review+merge, or are you just happy to self-merge from here on ?
I don't expect to keep up with this forever anyway, but hopefully you'll gather a new group to take it forward.

**Comment by BHFock** [comment]
@pp-mo, please review and merge. 

Let's discuss next steps offline.

**Review by pp-mo — CHANGES_REQUESTED** [review]
Ok, the changes themselves are just fine, but the "shadow" notebook copies need to be renamed as well as the notebook files, as it doesn't know to do that automatically.
So, I think just 
```
rm notebooks/.notebook_shadow_copies/MeshCube_Extraction.md 
notebooks/.notebook_shadow_copies/Mesh_Connectivities_demo.md 
notebooks/.notebook_shadow_copies/mesh_from_numbers.md 
```

Then we should see that git/GitHub treats those as renames + small adjustments, as it does for the actual notebook changes.

**Comment by BHFock** [comment]
I deleted the shadow_copies in c4d22cb4c52ad9ddffc4effa10af8173096e179c

**Review by pp-mo — APPROVED** [review]
Great, that all seems to make perfect sense now.

**Pull request merged**
